### ISSUE TITLE
Battle lines still in English

### ISSUE THREAD

**Issue by rojamet** [ZhenjianYang/SoraVoice#12]
Hello,

Game: Trails in the Sky FC
Platform: Steam

I managed to install SoraVoice and get the dialog lines in JP, but the battle voice lines are still in English.

According to something I've read somewhere, I should have an in-game option for the battle lines, but my only choices are On/Off.

If I missed something or if you have an idea, it would be much appreciated. 

You have my thanks for that great mod by the way. Just having the JP dialogs makes it more enjoyable.

**Comment by rojamet** [comment]
I fixed the issue by using a third party "one click installer" for your mod (https://github.com/chyyran/skyinstaller)

For the sake of posterity and future reference for anyone, I'm still interested in the answer. Did I miss something? Did it happen because the voice files I had did not include the battle lines?

**Comment by ZhenjianYang** [comment]
Hi,

This mod only adds Japanese dialog dubs, there is a completely different mod (not authored by me) which adds the Japanese battle voice.   
So I think what you made wrong was that you didn't install the Japanese battle voice mod.

**Comment by rojamet** [comment]
Ah, fair enough, I assumed this mod did all the lines. Thanks for the clarification!
