### ISSUE TITLE
A tool for decoding .vag files.

### ISSUE THREAD

**Issue by MikuTsubasa** [ZhenjianYang/SoraVoice#13]
Um...hello. I'm new to github so I don't know if it's ok to post something like this in here. 

I just wanted to ask if you can also make a voice mod for the battle? I found a tool to decode the files inside the "se" folder which contains the voice files for the battle, minigames in sun doors (3rd), when the main characters report their job to the bracer guild and some extra voice test in audio settings. The tool will convert the .vag into .wav.

I have a proof here that the tool is working:
https://www.youtube.com/watch?v=dIb9svb7g5Y&list=PLhuwB5dMEYX1REwgwJdgQW2AN5KllfxG9&index=2
I already tested it on Sora the 3rd, Zero and Ao Evo and it's working. I'm not sure on FC and SC Evo but maybe it's also working because they're just the same.

(Note: battle, minigames, etc.)
sora 3rd evo voices 
vic10001.vag - vic16115.vag
ao evo voices
ed7v0799.vag - ed7v4135.vag

Here's the link for the tool and I also added some notes on where did I get it.
https://www.mediafire.com/file/dbb63adot5aaudc/hevag_decoder.rar

I hope It helps, thanks for reading and also thank you very much for making these wonderful mod with your friends who helped. God bless all of you. 😀

**Comment by ZhenjianYang** [comment]
Your idea is quit interesting.
Now we are still working with voice scripts of the 3rd.
After they are finished, we will take a try of 'battle voice mod'.
But we can't promise anything more.

**Comment by MikuTsubasa** [comment]
Oh, thank you! I'll pray that you guys can make a mod for it and I'm so excited to hear one of my favorite voiced event in 3rd evo again. You know that Little Estelle part going into the forest, I laughed at the part where she sounded like she's planning something evil. (Now I know it's not, but maybe for the giant mushi, she's evil. Lolz!)
Now then, I'll close this issue (or maybe not an issue, maybe an idea or a request? A request for Bracers/Programmers?)
Again, Thank you for everything! Good Bye!
