### ISSUE TITLE
jp script in soravoicescrpit ?

### ISSUE THREAD

**Issue by mondaychicken** [ZhenjianYang/SoraVoice#14]
Hello.
I really appreciate your working.

Can you also make japanese script on Trails in the Sky fc ,sc, the3rd by Xseed ?

Thanks.

**Comment by ZhenjianYang** [comment]
I know the original PC versions of Sora are Japanese,
but is there any mod of Japanese translations for Xseed's trails in the sky?

**Comment by mondaychicken** [comment]
The modding way is just replacing specific file.

For example, only for dialogue script,                                     
  trails in the sky fc (Xseed)  ed6_dt01.dat,  ed6_dt01.dir  replace 
to sora no kiseki fc (original)  ed6_dt01.dat, ed6_dt01.dir.

Then,  instead of english, dialogue becomes japanese.

**Comment by ZhenjianYang** [comment]
I see.
Back to your question, about voice scripts for JP versions.
I know someone else are working for it, so there is a chance.
But I can't 100% promise.

**Comment by mondaychicken** [comment]
screenshot 1 (replaced dt01 and dt02 and new start)
https://imgur.com/a/o1RPl

screenshot 2 (replaced dt01 and dt02 but, played save file load)
https://imgur.com/a/iCFtR

Dialogue box's character name is english.  
  But, if it is new start, the name is japanese.  So it is not a problem.

If you think that it is a problem for all of the parts translation of trails in the sky,
  I don't think so.

Although  some parts is english,  
  it's enough to play the game by japanese.

reference site
http://modding.tistory.com/28?category=658987
Maybe, this site might be helpful.

Cheer up!!!

**Comment by ZhenjianYang** [comment]
Thank you.

But with this method, some Steam versions' features will be unavailable.
You can't save clear data after the ending of FC.
You won't receive Monster Note from Scherazard.
Mueller and Julia won't join your party in SC.
The Steam achievement 'Patient Plunderer' can never be earned.
etc.

I mentioned someone are working with voice scripts JP.
It will based on Steam versions' scripts. 
So no Steam versions' features will be lost.

**Comment by mondaychicken** [comment]
ok, I understand.

Thank you for answer.

Keep up the good work.
