### ISSUE TITLE
Voice won't come out

### ISSUE THREAD

**Issue by actrois** [ZhenjianYang/SoraVoice#15]
Continuation from #12, the voice won't come out in any dialogue.
The "Sora/Ao/Zero no Kiseki Voice Patch" text appeared in the game’s startup and when I press the hotkeys it shows the infos accordingly

I've tried latest version from GOG (fresh install) and steam, still doesn't work

here are screenshots of the folders:
Installation folder (steam):
![game_folder](https://user-images.githubusercontent.com/9760325/36829633-aa7fa32e-1d52-11e8-8b9a-0a9f2d70a427.PNG)

voice folder:
![voice_folder](https://user-images.githubusercontent.com/9760325/36829665-ddc5373a-1d52-11e8-8b27-fdf216a5d4f6.PNG)

dll folder:
![dll](https://user-images.githubusercontent.com/9760325/36829672-e3eb6ab2-1d52-11e8-81c8-fc152a897d32.PNG)

ogg folder:
![ogg_folder](https://user-images.githubusercontent.com/9760325/36829674-e4585e88-1d52-11e8-97cc-cdedabedc59f.PNG)

scena folder:
![scena](https://user-images.githubusercontent.com/9760325/36829675-e49ca818-1d52-11e8-80d0-da85938d19e0.PNG)

**Comment by ZhenjianYang** [comment]
I noticed that the scripts' filenames are changed.
This must be the problem.
Every script's filename contains 1 ~ 3 spaces, and you shouldn't remove them.

**Comment by actrois** [comment]
Oh dammit, it works :))

Seems like the spaces are removed when I downloaded it (I downloaded it from different source)
Many thanks, and sorry for bothering you with such stupid issue
