### ISSUE TITLE
Installed, have the "Voice Path" watermark when booting up game but no voices

### ISSUE THREAD

**Issue by ethanryan12** [ZhenjianYang/SoraVoice#22]
I used the voice files from here: https://mikutsubasa.wixsite.com/shinelikechestelle/downloads-vf

Here are some images of the files
![issue3](https://user-images.githubusercontent.com/7636947/42353995-72af8942-8089-11e8-8a60-68d79ffdc5f1.PNG)
![issue2](https://user-images.githubusercontent.com/7636947/42353998-74dd11f8-8089-11e8-9b89-582ced77ab7b.PNG)
![issue1](https://user-images.githubusercontent.com/7636947/42354000-76af7b74-8089-11e8-9bd3-46096d6bf7dd.PNG)

**Comment by ethanryan12** [comment]
Oh yeah I know that I don't have the voice scripts but I can't find this "scena" folder you mention

**Comment by ZhenjianYang** [comment]
Get the voice scripts here:
https://github.com/ZhenjianYang/SoraVoice#voice-scripts
https://github.com/ZhenjianYang/SoraVoiceScripts

**Comment by ethanryan12** [comment]
No no, I have them, it's just that I don't know what exactly to put in the voice folder, again you said to put in something called "scena"

**Comment by ZhenjianYang** [comment]
Extract en.fc with a file archiver like 7zip.
Then you will get a folder 'scena', copy this folder to the 'voice' folder

**Comment by ethanryan12** [comment]
just the scena folder then? cause I already did that but I put the en.fc too lemme try it

**Comment by ethanryan12** [comment]
![issue4](https://user-images.githubusercontent.com/7636947/42391040-9367fc52-8113-11e8-8259-a13cf5b8e6d1.PNG)
No good

**Comment by ZhenjianYang** [comment]
If you have the voice patch installed correctly, it most likely be one of these two reasons:
1. You game is not up to date. 
The voice patch only supports games with latest update installed.
Try to update your game.
2. Conflicts with other Mods. 
I noticed that there are some files in your game's installation folder which are not included in the original game. Did they come from another Mod? Try to remove them and verify integrity of game files in your Steam client.

By the way, if the voice patch is installed correctly, the structure will look like this:
```
Game's Installation Folder/
├── dinput8.dll
└── voice/
    ├── ed_voice.dll
    ├── ed_voice.ini (generated after launching the game)
    ├── scena/
    |   └──... (._SN files)
    | 
    └── ogg/
        └──... (.ogg files)
```

**Comment by ethanryan12** [comment]
I did verify intergity last night but i'm gonna uninstall and reinstall

**Comment by ZhenjianYang** [comment]
Can you post a capture of the folder scena ?

**Comment by ethanryan12** [comment]
![issue](https://user-images.githubusercontent.com/7636947/42394872-4f9e882a-8121-11e8-8d34-42cd863ab89f.PNG)
![issue0](https://user-images.githubusercontent.com/7636947/42394879-55d3ef50-8121-11e8-98c2-c6a796984a22.png)
![issue1](https://user-images.githubusercontent.com/7636947/42394880-55ee8ffe-8121-11e8-8e4d-cb64a4177c8c.PNG)

**Comment by ZhenjianYang** [comment]
I mean taking a capture inside the folder voice/scena

**Comment by ethanryan12** [comment]
I have no ._SN files in my scena folder, I clicked the doAll.bat in my en.fc folder and took the scena folder out of temp

**Comment by ZhenjianYang** [comment]
You should follow [These Steps](https://github.com/ZhenjianYang/SoraVoiceScripts#follow-these-steps) to generate voice scripts.
Or get them at [Release](https://github.com/ZhenjianYang/SoraVoiceScripts/releases/latest).

**Comment by ethanryan12** [comment]
okay, well I went in the folder from git instead of straight downloading it, and the scena folder has stuff in it so I think it's working

**Comment by ethanryan12** [comment]
K that worked thx
