### ISSUE TITLE
Patch doesn't work on the latest update for Sora

### ISSUE THREAD

**Issue by shrik450** [ZhenjianYang/SoraVoice#26]
As of 2019-03-25, there has been an update to the Trails in the Sky series on steam which breaks the mod on all three games. 

Ref. https://www.reddit.com/r/Falcom/comments/b5010r/evo_voice_mod_stopped_working_after_recent_steam/

**Comment by ZhenjianYang** [comment]
Hi,
Thanks for your report.
I will fix it on Thursday.

**Comment by Marcox94** [comment]
ZhenjianYang: thanks, now all works!
