### ISSUE TITLE
Steam Version Trails in the Sky New Update

### ISSUE THREAD

**Issue by joshua-casey** [ZhenjianYang/SoraVoice#31]
Hi devs and community,

Around 5 December 2019, steam versions received an update, and the releases are no longer working. Tested on FC / SC Steam version, not sure about 3rd or the other versions, but 3rd also have a Steam update, so I assume it would also not work.

There is a workaround for now in steam (at least it works for me), by enabling the Beta options for March 24th 2019 version, I can keep running the voice mod.

Thank you.

**Comment by ZhenjianYang** [comment]
Hi,
Thanks for reporting.
I will try to fix in this weekend.

**Comment by ZhenjianYang** [comment]
Hi,
I finished the fix.
Please download the new release [here](https://github.com/ZhenjianYang/SoraVoice/releases/latest).

**Comment by joshua-casey** [comment]
Confirmed that it works for FC, SC, and 3rd for current Steam version.

Thank you. Closing the issue.
