### ISSUE TITLE
Game immediately crashes after loading saved game

### ISSUE THREAD

**Issue by Nikodemsky** [ZhenjianYang/SoraVoice#33]
Win 10 x64
Steam Version of _Trails in the Sky FC_, freshly installed.
Latest version of SoraVoice(20191210)
Latest version of SoraVoiceScripts(en.fc - 20171018)
ed6501 is present
It happens both on dx9 and dx8 versions.
Have tried both dsound.dll and dinput8.dll)
I haven't used any mods before - so the "before" saves are made without the mod itself.

The game simply crashes after loading any "before mod" save. New game works perfectly.

Is there a way to play game with my saved games from before i used the mod, or starting the new game is must?

**Comment by ZhenjianYang** [comment]
Hi,
Unfortunately the savedata compatibility problem is an issue of the game, not of the mod.
You will face the same problem if you are playing with English version but trying to load a savedata saved in Japanese version.
But most savedatas NOT saved at the end of a chapter should be compatible.
I recommend you try other savedatas.

**Comment by Nikodemsky** [comment]
Got it, thanks.
