### ISSUE TITLE
the 3rd Voice file not working

### ISSUE THREAD

**Issue by ZeroVG** [ZhenjianYang/SoraVoice#34]
Couple of years ago i set up the voice files for trails in the sky the 3rd, worked great. But, after a couple of patches it seems the old file isn't working anymore? anyway, a month ago or so, i downloaded the latest SoraVoice file from here (SoraVoice-20191210) and replaced it with the old one, didn't seem to work. tried to start a new game to see a cutscene to test it out, and nothing. i'd really appreciate the help, i'll post some screenshots below.

![image](https://user-images.githubusercontent.com/60144920/77176237-d6592980-6ad4-11ea-9829-9f678625ff14.png)

![image](https://user-images.githubusercontent.com/60144920/77176302-ef61da80-6ad4-11ea-8816-64b5f984ccb2.png)

![image](https://user-images.githubusercontent.com/60144920/77176351-00aae700-6ad5-11ea-94c4-58b24c7ffff3.png)

Unsure if there is anything else significant enough to post a screenshot of. Please tell me if there is.

**Comment by ZhenjianYang** [comment]
Hi,
You didn't have the latest voice patch installed. ('Data modified' is 3/9/2019)
Please replace 'dsound.dll' & 'ed_voice.dll' with the ones in the [latest release](https://github.com/ZhenjianYang/SoraVoice/releases/latest). ('SoraVoice-20191210')
And please make sure your game is also up to date (with Dec 2019's update)

**Comment by ZeroVG** [comment]
oh damn, it wasn't xD.
well, i updated the following 3 in the screenshot
![image](https://user-images.githubusercontent.com/60144920/77181517-81b9ac80-6adc-11ea-856a-cda7f2eb548c.png)
i have also replaced the dsound.dll (tho it says it was modified on July 2019...oddly enough)

but for the life of me i cannot find the 2 xvid files, or the ed_voice.dll. I searched in the SoraVoice folder, and in here. As for the link you provided, i can only see download links to the SoraVoice folder and the dsound file (unless i'm missing something?) am i suppose to rename something? cause i do see some ed_voice files, but not .dll ones
![image](https://user-images.githubusercontent.com/60144920/77182191-6b602080-6add-11ea-9827-727ac1bf2af0.png)

![image](https://user-images.githubusercontent.com/60144920/77182220-774be280-6add-11ea-8c00-c9ec7c1b7424.png)

i'd appreciate further help.

**Comment by ZhenjianYang** [comment]
I don't know how you got these .vcxproj/.sln files, but they are not part of the voice patch.
You can simply remove them.
ed_voice.dll is in folder 'voice', and you should put it under [game folder]/voice/

**Comment by ZeroVG** [comment]
well i feel like an idiot....it was literally there all along...i just forgot to extract it......

well, it works fine now, thanks for the help! i really appreciate it :)
