### ISSUE TITLE
零轨版本不匹配

### ISSUE THREAD

**Issue by peaceshi** [ZhenjianYang/SoraVoice#35]
[ED_ZERO.zip](https://github.com/ZhenjianYang/SoraVoice/files/4892934/ED_ZERO.zip)
ED_ZERO.exe MD5:2E11021B05BE88BF7BFA25363C3B5884 是exe不是zip md5
[ed_voice.log](https://github.com/ZhenjianYang/SoraVoice/files/4892939/ed_voice.log)

碧轨没问题.排除注册表问题.

**Comment by ZhenjianYang** [comment]
您好，感谢您的反馈

问题的原因似乎是Release里的dinput.dll文件并非最新的
我已经更新了Release里的文件
请到[这里](https://github.com/ZhenjianYang/SoraVoice/releases/latest)下载最新的文件，应该可以解决这个问题

**Comment by peaceshi** [comment]
使用最新Release问题解决. 谢谢.
