### ISSUE TITLE
[SOLVED] Voice files not working in Zero no Kiseki.

### ISSUE THREAD

**Issue by RaienryuuNoNatsu** [ZhenjianYang/SoraVoice#5]
So, hopefully I'll be able to explain the whole thing. Let's start with the version. I'm using the Chinese PC version, updated to 1.4. The game works fine the way it is.

Now, I followed the steps as per the guide. Dropped the dinput8.dll into the main folder (where ED_ZERO.exe is). I've also tried dsound.dll as a fool proof, didn't change anything.

I created the voice folder, downloaded ZeroAoVoiceScripts project (to be exact, the file cn.zero_170617.7z), and dropped the scena folder in the voice folder. I did the same for the dll folder with the audio libraries.

So, my voice folder now contains the dll folder, the scena folder, and ed_voice.dll.

Dumped the Evolution version, converted part of the at9 files to .wav, and then to ogg through ffmpeg. Do I have to convert them all for this to work? I converted only the first folder as a test, because there's really a lot of stuff.

Anyway, I created the ogg folder inside the voice one, and dropped the ogg inside it.

General
Complete name               : D:\where\the\game\is\零の軌跡\voice\ogg\v0100002.ogg
Format                      : Ogg
File size                   : 28.8 KiB
Duration                    : 3 s 509 ms
Overall bit rate mode       : Variable
Overall bit rate            : 67.1 kb/s
Writing application         : Lavc57.104.100 libvorbis

Audio
ID                          : 2206610650 (0x838634DA)
Format                      : Vorbis
Format settings, Floor      : 1
Duration                    : 3 s 509 ms
Bit rate mode               : Variable
Bit rate                    : 80.0 kb/s
Channel(s)                  : 1 channel
Sampling rate               : 48.0 kHz
Compression mode            : Lossy
Stream size                 : 34.3 KiB
Writing library             : Lavf57.79.100

Let me know if the Lavf library may be the problem in terms of decoding, and I'll just re-encode the files. Expected command line and bitrate would be appreciated if you happen to know. Also, I realized that it should be a stereo file, and also can't get it to use the bitrate I want.

When I start the game, it also doesn't create the ed_voice.ini, which should be in the voice folder when the game launches.

What am I doing wrong?

UPDATE: Is it normal that the extracted WAV is also a mono channel file? Also, tried another OggEnc, which uses LibVorbis instead of Lavf. It didn't change anything.

**Comment by ZhenjianYang** [comment]
Where did you get your game?   
Voice patch will only work for *Zero no kiseki* published by Joyoland in Mainland China, Chinese Simplified. And 1.1 patch should be applied. (There's only one update, so how did you update the game to 1.4?)   
Version 1.1 has 1000 savedata slots, while 1.0 only has 100. Check it to confirm your game's version.   
Joyoland also published this game in JOYO platform and Cubejoy platform, these two versions are also supported. But the one published in TGP/Wegame platform is not.    

And the extracted  wav is mono channel, because the original at9 files are mono.

**Comment by RaienryuuNoNatsu** [comment]
I did change the directory manually, but I do remember the default one being "joyland\ED_ZERO". Im positive about the joyland part. The 1.4 thing was my misunderstanding, and if I check ED_ZERO.exe it's the 1.0 version.

> And the extracted wav is mono channel, because the original at9 files are mono.

I thought I was doing something wrong, but if it's normal, then cool. Can you confirm if I'm doing everything right, except for the missing update?

**Comment by ZhenjianYang** [comment]
I didn't find anything wrong except for the game's version.
Your game is 1.0 so voice patch won't work.

Here's the download link of 1.1 patch (It's a online storage link, but it was given by Joyoland, the game's publisher):   
[https://pan.baidu.com/s/1jGjy62M](https://pan.baidu.com/s/1jGjy62M)
You can download it by clicking the write button with a download icon and text '下载(10.7M)'    

But you may need to reactivate your game after applying the update, and it seems the activating server has been shutdown quite long before. I'm not very sure, so make a backup.

**Comment by RaienryuuNoNatsu** [comment]
I see, at least I've done everything correctly so far. Now, I'm actually a bit confused here. I tried the first scene all yesterday, so I didn't notice until now. When I updated my last post, that was the last time I opened the game. Now that I'm here, I noticed something.

<blockquote class="imgur-embed-pub" lang="en" data-id="dSRJykM"><a href="//imgur.com/dSRJykM">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by ZhenjianYang** [comment]
Your game is 1.0.
Savedata numbers starting from 1000 are prepared for the clear savedata which can only be loaded in the main menu to start a new game+.

And one more difference between 1.0 and 1.1 is, 1.1's savedata number has 5 digits (00001), but 1.0's is 4 digits.

**Comment by RaienryuuNoNatsu** [comment]
Oh, I got it to work. Yes, with 1.1 works perfectly. When launched, I got a pop uppointing to the voice directory. This is awesome, thank you very much for making this project a reality (I'm honestly really happy atm)! :D

I have a few questions left:
1) I have nothing against the Chinese version, in absolutely no way, but I can read Japanese instead, and I was going to buy that one too. From what I read, Falcom used the Chinese version and put Japanese text in it. So I was wondering, isn't there a chance the patch could work? Or is there something Joyoland did, that only they can do to the code/engine/whatever, that makes this patch not work with the Japanese game?
2) I also have the BGM from the Evolution game. I believe I just have to overwrite the originals, right? Should be pretty straightforward.
3) I have constant flickering about every 3 to 5 seconds. It started after I toggled a setting in the Config.exe launcher, but I don't know what it is, so I'm not sure that's exactly the case.

Again, really awesome project, and I can't wait to do the same for Ao no Kiseki.^^

**Comment by ZhenjianYang** [comment]
1. Voice patch won't work for the Japanese PC version published by Falcom, because every version's game has its own 'running parameters'. (Even Joyoland's 1.1 zero and 1.0 zero are different.) Voice patch won't work if these parameters are not set correctly.    
But it seems it is possible to put PSP's scripts into PC version.(Voice scripts for the Japanese PSP games are also done.) I don't know too much about it, so please Google it by yourself.

2. Yes, I think it will work.

3. The PC port done by Joyoland is not very well. The flickering is caused by the porting. Playing game with full screen mode, or avoiding to switch to another window after the game launching may reduce the chance of flickering.   

And just now, the voice scripts were updated. Fix a bug of Zero, which may cause some events not triggerable.

**Comment by RaienryuuNoNatsu** [comment]
1) That's unfortunate, but I can live with it as long as I can have voices.
2) Great, I'd like to record it when the English patch will be completed, so that's when I'll use the Evo BGM.
3) Got it, I'll see if I'm lucky.

And thanks for the update, I've just applied it to the game.
