### ISSUE TITLE
Will this project support Wegame version in the future days?

### ISSUE THREAD

**Issue by Autliety** [ZhenjianYang/SoraVoice#7]
Hope the Wegame version of Aonokiseki/Zeronokiseki can be supported in the future update! I'm quite in need of this, please!

**Comment by ZhenjianYang** [comment]
Sorry, they are not supported and perhaps will never be.
Games in Wegame Platform are protected by Tencent Protect System which stops us debugging and modifying any games' data.   
We have to crack TP System before we can let the patch work.
This is beyond my ability.

**Comment by Autliety** [comment]
Well, since it's impassible to modifying it, is there any methods to read game memory and use the outside voice tool, just as ZeroAoVoiceTool used to do?

**Comment by ZhenjianYang** [comment]
No.
ZeroAoVoiceTool is more impossible, it couldn't read any data from the game. (Stopped by TP System)
While the voice patch could read a little data in some way.

**Comment by Autliety** [comment]
Oh I see, sorry to issue this. I'm goint to buy an other version of game maybe. No minder close it:)
