### ISSUE TITLE
[Bug report] causes window restore failed bug

### ISSUE THREAD

**Issue by Autliety** [ZhenjianYang/SoraVoice#8]
If the game AoNoKiseki(joyoland) running under 1280*800 full screen with SoraVoice, it may sometimes cause the game unable to restore from a minimized status.

To trigger the bug: 
1. fully install the game and SoraVoice
2. run the game under 1280*800 full screen
3. minimize the game by press tab+alt, or switch window by alt+tab
4. go back to game
5. game would become a full white screen and drop a message 'リストア失敗' (RESTORE FAILED in japaness). Any key pressed will have no reply in the white screen except alt+F4 to quit it.
6. unable the SoreVoice by renaming dinput8.dll, or just playing the game in window rather than full screen will not trigger this.

Running Platform:
AoNoKiseki (Joyoland version) under windows 10 Creators Update, 1280*800
Macbook Pro, 13 inch, Mid-2012 with Bootcamp Windows

**Comment by RaienryuuNoNatsu** [comment]
Hi, Autliety. ZhenjianYang may be busy working on stuff, so I'm dropping by the answer for him. I'm no programmer, so let's go with the simple answer. He read this issue, and he's going to fix it right away, as it's an important tool for the patch to work.

An answer from him should come soon, he's usually pretty fast.

**Comment by Autliety** [comment]
Ok, waiting for good news :)

**Comment by ZhenjianYang** [comment]
Thank you for your report.
This bug also affects Sora and Zero, so I need some time to fix it.

**Comment by ZhenjianYang** [comment]
This bug has been fixed.
Please get the new release [here](https://github.com/ZhenjianYang/SoraVoice/releases/latest).
