### ISSUE TITLE
[Bug Report] Sidequest Crash

### ISSUE THREAD

**Issue by zander1995** [ZhenjianYang/SoraVoice#9]
Info: "Election Office Assault" hidden quest, with Sherazard as a companion. The game closes when trying to load the next cutscene.

When: Reporting the culprit to Sherazard. When the cutscene fades and loads the next one, the window closes. I reproduced this multiple times.

Save Data: https://mega.nz/#!oop1GQyB!DWVyJGm7ZqOX05fw3x5OcrBlj4iDVfa7LKXPCTfAXzU

Turning the voice patch off fixed the issue. It's most likely an issue with the script involving the sidequest.

**Comment by ZhenjianYang** [comment]
Thank you for your report.
It is a bug of the scripts, and I know what causes it.
But I need to check if other scripts also have this problem, so the new release will still take some time.
[This](https://drive.google.com/open?id=0BwmmgrbwtZzaUTE5bTJoVVhJUDg) is a temporary fix, only for this quest.

**Comment by ZhenjianYang** [comment]
The new release of the scripts:
https://github.com/ZhenjianYang/SoraVoice/releases/latest
